<?php if ( ! defined( 'ABSPATH' ) ) {
	die; } // Cannot access directly.

//
// Create a section
//
WPGP::createSection(
	$wpgp_page_opts,
	array(
		'title'  => __( 'General', 'wpgp-wordpress-slider' ),
		'icon'   => 'fa fa-puzzle-piece',
		'fields' => array(

			array(
				'type'    => 'content',
				'content' => '<div class="wpgp--menu-detail">
									<strong>General</strong>
									<a href="https://grandplugin.com/support-forum/" class="">Need Help?</a>
									<br>
									<p>General settings connecting the most important part of the slider. Responsive width and responsive hide are most important. Slider skin and slider content, you can control as you wish individually. And retrieve the posts we ensure that the most advanced query we provided through this plugin.</p>
								</div>',
			),

			array(
				'id'         => 'wpgp_section_title_show',
				'type'       => 'switcher',
				'title'      => __( 'Show the section title', 'wpgp-wordpress-slider' ),
				'subtitle'   => __( 'Show/Hide the slider section title.', 'wpgp-wordpress-slider' ),
				'text_on'    => __( 'Show', 'wpgp-wordpress-slider' ),
				'text_off'   => __( 'Hide', 'wpgp-wordpress-slider' ),
				'text_width' => 75,
				'default'    => true,
			),
			array(
				'id'         => 'wpgp_section_title_margin_bottom',
				'type'       => 'slider',
				'title'      => __( 'Section Title Margin Bottom', 'wpgp-wordpress-slider' ),
				'subtitle'   => __( 'Set margin bottom form section title.', 'wpgp-wordpress-slider' ),
				'unit'       => 'px',
				'default'    => 10,
				'dependency' => array( 'wpgp_section_title_show', '==', 'true' ),
				'class'      => 'wpgp--width-50',
			),
			array(
				'id'         => 'wpgp_slider_full_width_show',
				'type'       => 'switcher',
				'title'      => __( 'Turn on full width slider', 'wpgp-wordpress-slider' ),
				'subtitle'   => __( 'On/Off the full width slider.', 'wpgp-wordpress-slider' ),
				'text_on'    => __( 'On', 'wpgp-wordpress-slider' ),
				'text_off'   => __( 'Off', 'wpgp-wordpress-slider' ),
				'text_width' => 60,
				'default'    => true,
			),
			array(
				'id'          => 'wpgp_slider_width',
				'type'        => 'spacing',
				'title'       => __( 'Slider Width', 'wpgp-wordpress-slider' ),
				'subtitle'    => __( 'Slider maximum width in responsive view.', 'wpgp-wordpress-slider' ),
				'top_icon'    => '<i class="fa fa-desktop"></i>',
				'right_icon'  => '<i class="fa fa-laptop"></i>',
				'bottom_icon' => '<i class="fa fa-tablet"></i>',
				'left_icon'   => '<i class="fa fa-mobile-phone"></i>',
				'default'     => array(
					'top'    => '1280', // Desktop.
					'right'  => '1024', // Laptop.
					'bottom' => '767', // Tablet.
					'left'   => '480', // Mobile.
					'unit'   => 'px',
				),
				'dependency'  => array( 'wpgp_slider_full_width_show', '==', 'false' ),
				'class'       => 'wpgp--no-placeholder',
			),
			array(
				'id'       => 'wpgp_slider_height_mode',
				'type'     => 'button_set',
				'title'    => __( 'Height Mode', 'wpgp-wordpress-slider' ),
				'subtitle' => __( 'Set slider maximum height mode.', 'wpgp-wordpress-slider' ),
				'options'  => array(
					'auto'   => __( 'Auto', 'wpgp-wordpress-slider' ),
					'custom' => __( 'Custom', 'wpgp-wordpress-slider' ),
				),
				'default'  => 'custom',
			),
			array(
				'id'          => 'wpgp_slider_height',
				'type'        => 'spacing',
				'title'       => __( 'Slider Height', 'wpgp-wordpress-slider' ),
				'subtitle'    => __( 'Slider maximum height in responsive view.', 'wpgp-wordpress-slider' ),
				'top_icon'    => '<i class="fa fa-television"></i>',
				'right_icon'  => '<i class="fa fa-desktop"></i>',
				'bottom_icon' => '<i class="fa fa-tablet"></i>',
				'left_icon'   => '<i class="fa fa-mobile-phone"></i>',
				'default'     => array(
					'top'    => '775',
					'right'  => '700',
					'bottom' => '600',
					'left'   => '400',
					'unit'   => 'px',
				),
				'class'       => 'wpgp--no-placeholder',
				'dependency'  => array( 'wpgp_slider_height_mode', '==', 'custom' ),
			),
			array(
				'id'       => 'wpgp_slider_skin',
				'type'     => 'image_select',
				'title'    => __( 'Slider Skin', 'wpgp-wordpress-slider' ),
				'subtitle' => __( 'Choose a slider skin, how it should look like.', 'wpgp-wordpress-slider' ),
				'options'  => array(
					'skin-1' => WPGP_WORDPRESS_SLIDER_DIR_URL_FILE . 'admin/img/slider-skin/skin-1.jpg',
					'skin-2' => WPGP_WORDPRESS_SLIDER_DIR_URL_FILE . 'admin/img/slider-skin/skin-2.jpg',
					'skin-3' => WPGP_WORDPRESS_SLIDER_DIR_URL_FILE . 'admin/img/slider-skin/skin-3.jpg',
				),
				'default'  => 'skin-1',
			),
			array(
				'id'         => 'wpgp_carousel_focus',
				'type'       => 'switcher',
				'title'      => __( 'Focus on Middle', 'wpgp-wordpress-slider' ),
				'subtitle'   => __( 'On/Off focus on middle for immersive carousel.', 'wpgp-wordpress-slider' ),
				'text_on'    => __( 'On', 'wpgp-wordpress-slider' ),
				'text_off'   => __( 'Off', 'wpgp-wordpress-slider' ),
				'text_width' => 60,
				'default'    => false,
				'dependency' => array( 'wpgp_slider_skin', '==', 'skin-2' ),
			),
			array(
				'id'         => 'wpgp_carousel_aspect_ratio',
				'type'       => 'button_set',
				'title'      => __( 'Center slide Aspect Ratio', 'wpgp-wordpress-slider' ),
				'subtitle'   => __( 'Set aspect ratio for center slide.', 'wpgp-wordpress-slider' ),
				'options'    => array(
					'1.5' => __( 'Single', 'wpgp-wordpress-slider' ),
					'3'   => __( 'Triple', 'wpgp-wordpress-slider' ),
					'5'   => __( 'Quintuple', 'wpgp-wordpress-slider' ),
					'7'   => __( 'Septuple', 'wpgp-wordpress-slider' ),
					'9'   => __( 'Nonuple', 'wpgp-wordpress-slider' ),
				),
				'default'    => '7',
				'dependency' => array( 'wpgp_slider_skin', '==', 'skin-2' ),
			),
			array(
				'type'    => 'heading',
				'content' => __( 'Query', 'wpgp-wordpress-slider' ),
			),
			array(
				'id'          => 'wpgp_post_types_select',
				'type'        => 'select',
				'title'       => __( 'Source', 'wpgp-wordpress-slider' ),
				'subtitle'    => __( 'Select post type/s to make source of posts.', 'wpgp-wordpress-slider' ),
				'placeholder' => __( 'Select posts', 'wpgp-wordpress-slider' ),
				'chosen'      => true,
				'ajax'        => true,
				'multiple'    => true,
				'sortable'    => true,
				'options'     => 'post_types',
				'default'     => 'post',
				'class'       => 'wpgp--width-50',
			),
			array(
				'id'       => 'wpgp_post_include_exclude_set',
				'type'     => 'button_set',
				'title'    => __( 'Include/Exclude Post', 'wpgp-wordpress-slider' ),
				'subtitle' => __( 'Allowing or denying the post retrieve.', 'wpgp-wordpress-slider' ),
				'options'  => array(
					'include' => __( 'Include', 'wpgp-wordpress-slider' ),
					'exclude' => __( 'Exclude', 'wpgp-wordpress-slider' ),
				),
				'default'  => 'include',
			),
			array(
				'id'          => 'wpgp_post_include_exclude_by',
				'type'        => 'select',
				'title'       => __( 'Include/Exclude By', 'wpgp-wordpress-slider' ),
				'subtitle'    => __( 'Show posts with/without taxonomy or specific.', 'wpgp-wordpress-slider' ),
				'chosen'      => true,
				'placeholder' => __( 'Select an option', 'wpgp-wordpress-slider' ),
				'options'     => array(
					'categories' => __( 'categories', 'wpgp-wordpress-slider' ),
					'tags'       => __( 'tags', 'wpgp-wordpress-slider' ),
					'specific'   => __( 'Specific', 'wpgp-wordpress-slider' ),
				),
			),
			array(
				'id'          => 'wpgp_post_include_exclude_category',
				'type'        => 'select',
				'title'       => __( 'Select with CPT (custom post type) categories', 'wpgp-wordpress-slider' ),
				'placeholder' => 'Select a category',
				'chosen'      => true,
				'ajax'        => true,
				'multiple'    => true,
				'sortable'    => true,
				'options'     => 'categories',
				'dependency'  => array( 'wpgp_post_include_exclude_by', '==', 'categories' ),
				'class'       => 'wpgp--width-50',
			),
			array(
				'id'          => 'wpgp_post_include_exclude_tag',
				'type'        => 'select',
				'title'       => __( 'Select with CPT (custom post type) categories', 'wpgp-wordpress-slider' ),
				'placeholder' => 'Select a tag',
				'chosen'      => true,
				'ajax'        => true,
				'multiple'    => true,
				'sortable'    => true,
				'options'     => 'tags',
				'dependency'  => array( 'wpgp_post_include_exclude_by', '==', 'tags' ),
				'class'       => 'wpgp--width-50',
			),
			array(
				'id'          => 'wpgp_specific_post_select',
				'type'        => 'select',
				'title'       => __( 'Select with posts', 'wpgp-wordpress-slider' ),
				'placeholder' => 'Select posts',
				'chosen'      => true,
				'ajax'        => true,
				'multiple'    => true,
				'sortable'    => true,
				'options'     => 'posts',
				'dependency'  => array( 'wpgp_post_include_exclude_by', '==', 'specific' ),
				'class'       => 'wpgp--width-50',
			),
			array(
				'id'       => 'wpgp_post_order',
				'type'     => 'select',
				'title'    => __( 'Order', 'wpgp-wordpress-slider' ),
				'subtitle' => __( 'Arranging posts smallest to largest or reverse.', 'wpgp-wordpress-slider' ),
				'options'  => array(
					'ASC'  => 'ASC',
					'DESC' => 'DESC',
				),
				'default'  => 'DESC',
			),
			array(
				'id'       => 'wpgp_post_order_by',
				'type'     => 'select',
				'title'    => __( 'Order By', 'wpgp-wordpress-slider' ),
				'subtitle' => __( 'Sort retrieved posts according ot your selected order.', 'wpgp-wordpress-slider' ),
				'options'  => array(
					'none'          => 'None',
					'ID'            => 'ID',
					'author'        => 'Author',
					'title'         => 'Title',
					'name'          => 'Name',
					'type'          => 'Type',
					'date'          => 'Date',
					'modified'      => 'Modified',
					'parent'        => 'Parent',
					'rand'          => 'Rand',
					'comment_count' => 'Comment Count',
					'relevance'     => 'Relevance',
				),
			),
			array(
				'id'         => 'wpgp_sticky_post_ignore',
				'type'       => 'switcher',
				'title'      => __( 'Ignore Sticky Post', 'wpgp-wordpress-slider' ),
				'subtitle'   => __( 'Hide sticky posts.', 'wpgp-wordpress-slider' ),
				'text_on'    => __( 'Yes', 'wpgp-wordpress-slider' ),
				'text_off'   => __( 'No', 'wpgp-wordpress-slider' ),
				'text_width' => 70,
				'default'    => true,
				'dependency' => array( 'wpgp_post_include_exclude_by', '==', '' ),
			),
			array(
				'id'         => 'wpgp_post_max_number',
				'type'       => 'number',
				'title'      => __( 'Total Posts', 'wpgp-wordpress-slider' ),
				'subtitle'   => __( 'Show maximum number of posts.<br>(-1 stands for no limit)', 'wpgp-wordpress-slider' ),
				'default'    => -1,
				'dependency' => array( 'wpgp_post_include_exclude_by', '==', '' ),
			),

			array(
				'type'    => 'heading',
				'content' => __( 'Content', 'wpgp-wordpress-slider' ),
			),
			array(
				'id'         => 'wpgp_post_title_show',
				'type'       => 'switcher',
				'title'      => __( 'Show The Post Title', 'wpgp-wordpress-slider' ),
				'subtitle'   => __( 'Show/Hide the post title.', 'wpgp-wordpress-slider' ),
				'text_on'    => __( 'Show', 'wpgp-wordpress-slider' ),
				'text_off'   => __( 'Hide', 'wpgp-wordpress-slider' ),
				'text_width' => 75,
				'default'    => true,
			),
			array(
				'id'          => 'wpgp_slider_title_html_tag',
				'type'        => 'select',
				'title'       => __( 'Slider Title HTML Tag', 'wpgp-wordpress-slider' ),
				'subtitle'    => __( 'Select HTML tag for the post title.', 'wpgp-wordpress-slider' ),
				'placeholder' => 'Select an option',
				'options'     => array(
					'h1' => 'H1',
					'h2' => 'H2',
					'h3' => 'H3',
					'h4' => 'H4',
					'h5' => 'H5',
					'h6' => 'H6',
				),
				'default'     => 'h2',
				'dependency'  => array( 'wpgp_post_title_show', '==', true ),
			),
			array(
				'id'         => 'wpgp_slider_desc_show',
				'type'       => 'switcher',
				'title'      => __( 'Show the Post Description', 'wpgp-wordpress-slider' ),
				'subtitle'   => __( 'Show/Hide the slider description.', 'wpgp-wordpress-slider' ),
				'text_on'    => __( 'Show', 'wpgp-wordpress-slider' ),
				'text_off'   => __( 'Hide', 'wpgp-wordpress-slider' ),
				'text_width' => 75,
				'default'    => true,
			),
			array(
				'id'         => 'wpgp_slider_desc_mobile_hide',
				'type'       => 'checkbox',
				'title'      => __( 'Hide on Mobile', 'wpgp-wordpress-slider' ),
				'subtitle'   => __( 'Hide the slider description on mobile screen?', 'wpgp-wordpress-slider' ),
				'label'      => 'Yes, Please do it.',
				'default'    => true,
				'dependency' => array( 'wpgp_slider_desc_show', '==', true ),
			),
			array(
				'id'         => 'wpgp_post_date',
				'type'       => 'switcher',
				'title'      => __( 'Show The Post Date', 'wpgp-wordpress-slider' ),
				'subtitle'   => __( 'Show/Hide the post date.', 'wpgp-wordpress-slider' ),
				'text_on'    => __( 'Show', 'wpgp-wordpress-slider' ),
				'text_off'   => __( 'Hide', 'wpgp-wordpress-slider' ),
				'text_width' => 75,
				'default'    => true,
			),
			array(
				'id'         => 'wpgp_post_thumb_show',
				'type'       => 'switcher',
				'title'      => __( 'Show The Post Thumbnail', 'wpgp-wordpress-slider' ),
				'subtitle'   => __( 'Show/Hide the post thumbnail.<br><span style="color: #f44336;">If you disable thumbnails, Immersive carousel will not working.</span>', 'wpgp-wordpress-slider' ),
				'text_on'    => __( 'Show', 'wpgp-wordpress-slider' ),
				'text_off'   => __( 'Hide', 'wpgp-wordpress-slider' ),
				'text_width' => 75,
				'default'    => true,
			),
			array(
				'id'         => 'wpgp_slider_bg_color',
				'type'       => 'color',
				'title'      => __( 'Slider Background Color', 'wpgp-wordpress-slider' ),
				'subtitle'   => __( 'Set a slider background color.', 'wpgp-wordpress-slider' ),
				'default'    => '#03a9f4',
				'dependency' => array( 'wpgp_post_thumb_show', '==', false ),
			),

		),
	)
);
